const INCREASE_ITEM = 'INCREASE_ITEM';
const DECREASE_ITEM = 'DECREASE_ITEM';
const REMOVE_ITEM = 'REMOVE_ITEM';
const CLEAR_CART = 'CLEAR_CART';

export { INCREASE_ITEM, DECREASE_ITEM, REMOVE_ITEM, CLEAR_CART };
